# Generated by Django 4.1.7 on 2023-03-23 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('RJ', 'Rio de Janeiro'), ('MT', 'Mato Grosso'), ('RS', 'Rio Grande do Sul'), ('DF', 'Distrito Federal'), ('AL', 'Alagoas'), ('MS', 'Mato Grosso do Sul'), ('PB', 'Paraíba'), ('RO', 'Rondônia'), ('RN', 'Rio Grande do Norte'), ('MG', 'Minas Gerais'), ('CE', 'Ceará'), ('SP', 'São Paulo'), ('RR', 'Roraíma'), ('AC', 'Acre'), ('AP', 'Amapá'), ('PI', 'Piauí'), ('PE', 'Pernambuco'), ('PR', 'Paraná'), ('SE', 'Sergipe'), ('MA', 'Maranhão'), ('TO', 'Tocatins'), ('PA', 'Pará'), ('SC', 'Santa Catarina'), ('BA', 'Bahia')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.endereco'),
        ),
    ]
